POST http://localhost:3333/sapatos
Content-Type: application/json

{
    "tamanho": 37,
    "modelo": "Converse",
    "nome": "Shodun",
    "cor":"roxo escuro",
    "preco": 500
}


###

GET  http://localhost:3333/sapatos?search=Shodun

###

GET http://localhost:3333/sapatos

###

PUT  http://localhost:3333/sapatos/78e46487-25ca-43ad-b60f-6d4588a74279
Content-Type: application/json

{
    "tamanho": 43,
    "modelo": "vans",
    "nome": "esporte",
    "cor":"rosa claro",
    "preco": 8000
}

###

DELETE http://localhost:3333/sapatos/a0b41882-e5d8-47a1-ac94-42cb8d1f2ff8
###

PATCH http://localhost:3333/sapatos/ebcab52a-5c87-40e5-8451-d4557602b85e
Content-Type: application/json

{
    "preco": 7500
}